const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
const make=(tag,attrs={})=>{const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,String(v));return n};
let routes=[],selected=1,closed='open';
function draw(){const route=routes[selected],svg=$('route-drawing');if(!route)return;svg.replaceChildren();const sx=x=>40+x*820/136,sy=y=>28+y*500/117;
  for(let x=0;x<=136;x+=20)svg.append(make('line',{x1:sx(x),y1:28,x2:sx(x),y2:528,stroke:'#e1ded7','stroke-width':1}));for(let y=0;y<=117;y+=20)svg.append(make('line',{x1:40,y1:sy(y),x2:860,y2:sy(y),stroke:'#e1ded7','stroke-width':1}));
  svg.append(make('rect',{x:40,y:28,width:820,height:500,fill:'none',stroke:'#aaa69d'}));
  if(closed==='open'){const points=route.path_grid.map(([x,y])=>`${sx(x)},${sy(y)}`).join(' ');svg.append(make('polyline',{points,fill:'none',stroke:'#294b8d','stroke-width':5,'stroke-linecap':'round','stroke-linejoin':'round'}));const start=route.path_grid[0],end=route.path_grid.at(-1);svg.append(make('circle',{cx:sx(start[0]),cy:sy(start[1]),r:9,fill:'#294b8d'}),make('circle',{cx:sx(end[0]),cy:sy(end[1]),r:9,fill:'#9a4b55'}));$('route-readout').textContent=`${route.start.name} → ${route.end.name} / ${route.distance_m.toFixed(2)} m / ${route.path_grid.length} grid points`}
  else{$('route-readout').textContent=`${route.start.name} → ${route.end.name} / disconnected with door #${closed} closed`;const label=make('text',{x:450,y:282,'text-anchor':'middle',fill:'#294b8d','font-family':'Inter','font-size':29});label.textContent='No traversable route';svg.append(label)}
  const foot=make('text',{x:42,y:552,fill:'#69675f','font-family':'monospace','font-size':11});foot.textContent='SOURCE GRID COORDINATES / 0.10 M PITCH';svg.append(foot)}
function setDoors(which){closed=which;for(const [id,val] of [['door-open','open'],['door-one','17468'],['door-two','19504']])$(id).setAttribute('aria-pressed',String(val===which));draw()}
function choose(i){selected=i;closed='open';document.querySelectorAll('#route-pairs button').forEach((b,j)=>b.setAttribute('aria-current',String(j===i)));$('door-one').disabled=i!==1;$('door-two').disabled=i!==1;setDoors('open')}
fetch('media/ifc-routes.json').then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(data=>{routes=data;const wrap=$('route-pairs');wrap.replaceChildren(...routes.map((r,i)=>{const b=document.createElement('button');b.type='button';b.textContent=`${r.start.name} → ${r.end.name} / ${r.distance_m.toFixed(2)} m`;b.addEventListener('click',()=>choose(i));return b}));choose(1)}).catch(e=>{$('route-readout').textContent=`Route data unavailable: ${e.message}`});
$('door-open').addEventListener('click',()=>setDoors('open'));$('door-one').addEventListener('click',()=>setDoors('17468'));$('door-two').addEventListener('click',()=>setDoors('19504'));
