const D=id=>document.getElementById(id), NSD='http://www.w3.org/2000/svg';
const ds=(tag,attrs={})=>{const el=document.createElementNS(NSD,tag);for(const [key,val] of Object.entries(attrs))el.setAttribute(key,String(val));return el};
let dyn,selectedDyn=null,centerDyn=[660,340],sizeDyn=[1700,800],dragDyn=null;
const pos=n=>[n.x+420,n.y+260],byId=id=>dyn.nodes.find(n=>n.id===id);
function viewDyn(){const scale=Number(D('dynamo-zoom').value),width=sizeDyn[0]/scale,height=sizeDyn[1]/scale;D('dynamo-canvas').setAttribute('viewBox',`${centerDyn[0]-width/2} ${centerDyn[1]-height/2} ${width} ${height}`)}
function labelLines(label){const words=label.split(' '),lines=[''];for(const word of words){const i=lines.length-1;if((lines[i]+' '+word).length>21&&lines.length<3)lines.push(word);else lines[i]+=(lines[i]?' ':'')+word}return lines}
function drawDyn(){if(!dyn)return;const svg=D('dynamo-canvas'),map=new Map(dyn.nodes.map(n=>[n.id,n]));svg.replaceChildren();viewDyn();
  for(const edge of dyn.edges){const a=map.get(edge.source),b=map.get(edge.target);if(!a||!b)continue;const [ax,ay]=pos(a),[bx,by]=pos(b),active=selectedDyn&&(edge.source===selectedDyn||edge.target===selectedDyn);svg.append(ds('path',{d:`M${ax+170},${ay+37} C${(ax+bx+170)/2},${ay+37} ${(ax+bx+170)/2},${by+37} ${bx},${by+37}`,class:`dynamo-wire ${active?'active':''}`}))}
  for(const n of dyn.nodes){const [x,y]=pos(n),active=n.id===selectedDyn,connected=selectedDyn&&dyn.edges.some(e=>(e.source===selectedDyn&&e.target===n.id)||(e.target===selectedDyn&&e.source===n.id));const group=ds('g',{class:`dynamo-node ${active?'active':''} ${connected?'connected':''}`,tabindex:0,role:'button','aria-label':`Select Dynamo component ${n.name}`});group.append(ds('rect',{x,y,width:170,height:75,rx:2}));const lines=labelLines(n.name);lines.forEach((line,i)=>{const t=ds('text',{x:x+12,y:y+24+i*16});t.textContent=line;group.append(t)});group.addEventListener('click',()=>selectDyn(n.id));group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectDyn(n.id)}});svg.append(group)}
}
function detailDyn(){if(!selectedDyn)return;const n=byId(selectedDyn),incoming=dyn.edges.filter(e=>e.target===selectedDyn),outgoing=dyn.edges.filter(e=>e.source===selectedDyn);const detail=D('dynamo-detail');detail.replaceChildren();const head=document.createElement('div');head.className='dynamo-detail-title';head.textContent=n.name;const meta=document.createElement('span');meta.className='mono';meta.textContent=`${incoming.length} incoming / ${outgoing.length} outgoing · saved component ${n.id}`;const links=document.createElement('div');links.className='dynamo-detail-links';for(const [kind,edges] of [['IN',incoming],['OUT',outgoing]])for(const e of edges){const neighbor=byId(kind==='IN'?e.source:e.target),b=document.createElement('button');b.type='button';b.textContent=`${kind} ${e.output||'output'} → ${e.input||'input'} · ${neighbor.name}`;b.addEventListener('click',()=>jumpDyn(neighbor.id));links.append(b)}detail.append(head,meta,links)}
function selectDyn(id){selectedDyn=id;drawDyn();detailDyn()}
function jumpDyn(id){const n=byId(id);if(!n)return;const [x,y]=pos(n);centerDyn=[x+85,y+38];selectDyn(id)}
const canvas=D('dynamo-canvas');canvas.addEventListener('pointerdown',e=>{if(e.target.closest('.dynamo-node'))return;dragDyn=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragDyn)return;const zoom=Number(D('dynamo-zoom').value),width=sizeDyn[0]/zoom,height=sizeDyn[1]/zoom;centerDyn[0]-=(e.clientX-dragDyn[0])*width/canvas.clientWidth;centerDyn[1]-=(e.clientY-dragDyn[1])*height/canvas.clientHeight;dragDyn=[e.clientX,e.clientY];viewDyn()});canvas.addEventListener('pointerup',()=>dragDyn=null);canvas.addEventListener('pointercancel',()=>dragDyn=null);
D('dynamo-zoom').addEventListener('input',viewDyn);
fetch('media/dynamo-graphs.json').then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(all=>{dyn=all.find(g=>g.name==='kiarash taheri - mohammadreza hoseiny.dyn');if(!dyn)throw Error('co-named graph missing');const named=name=>dyn.nodes.find(n=>n.name===name)?.id;D('dynamo-start').addEventListener('click',()=>jumpDyn(named('Categories')));D('dynamo-filter').addEventListener('click',()=>jumpDyn(named('List.FilterByBoolMask')));D('dynamo-area').addEventListener('click',()=>jumpDyn(named('Surface.Area')));jumpDyn(named('All Elements of Category'))}).catch(e=>{D('dynamo-detail').textContent=`Saved graph unavailable: ${e.message}`});
