const S='http://www.w3.org/2000/svg';const I=id=>document.getElementById(id);const E=(tag,attrs={})=>{const n=document.createElementNS(S,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,String(v));return n};
let tower,graphMode='branch',graphCenter=[0,0],graphSize=[1,1],graphBase=[1,1],selectedId=null,dragPoint=null;
function graphNodes(){const branch=new Set(tower.analysis_branches.find(x=>x.ancestor_nodes===109).ancestor_ids);return tower.graph_nodes.filter(n=>n.position?.Bounds&&(graphMode==='all'||branch.has(n.id)))}
function graphView(){const zoom=Number(I('graph-scale').value),svg=I('tower-graph');graphSize=graphBase.map(v=>v/zoom);svg.setAttribute('viewBox',`${graphCenter[0]-graphSize[0]/2} ${graphCenter[1]-graphSize[1]/2} ${graphSize[0]} ${graphSize[1]}`)}
function drawGraph(reset=true){if(!tower)return;const svg=I('tower-graph'),nodes=graphNodes(),map=new Map(nodes.map(n=>[n.id,n]));const b=n=>n.position.Bounds;
  let minX=Math.min(...nodes.map(n=>Number(b(n).X))),maxX=Math.max(...nodes.map(n=>Number(b(n).X)+Number(b(n).W))),minY=Math.min(...nodes.map(n=>Number(b(n).Y))),maxY=Math.max(...nodes.map(n=>Number(b(n).Y)+Number(b(n).H)));
  if(reset){graphCenter=[(minX+maxX)/2,(minY+maxY)/2];graphBase=[(maxX-minX)*1.12,(maxY-minY)*1.25];I('graph-scale').value='2'}graphView();svg.replaceChildren();
  for(const w of tower.edges){const a=map.get(w.source),z=map.get(w.target);if(!a||!z)continue;const x1=Number(b(a).X)+Number(b(a).W),y1=Number(b(a).Y)+Number(b(a).H)/2,x2=Number(b(z).X),y2=Number(b(z).Y)+Number(b(z).H)/2;svg.append(E('path',{class:'wire',d:`M${x1},${y1} C${(x1+x2)/2},${y1} ${(x1+x2)/2},${y2} ${x2},${y2}`}))}
  const branch=new Set(tower.analysis_branches.find(x=>x.ancestor_nodes===109).ancestor_ids);
  for(const n of nodes){const p=b(n),rect=E('rect',{x:p.X,y:p.Y,width:p.W,height:p.H,rx:6,class:`node ${branch.has(n.id)?'':'dim'} ${selectedId===n.id?'selected':''}`,tabindex:0,role:'button','aria-label':`${n.name}, Grasshopper component`});rect.addEventListener('click',()=>selectGraphNode(n));rect.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectGraphNode(n)}});const title=E('title');title.textContent=n.name;rect.append(title);svg.append(rect)}
}
function selectGraphNode(n){selectedId=n.id;const incoming=tower.edges.filter(e=>e.target===n.id).length,outgoing=tower.edges.filter(e=>e.source===n.id).length;I('graph-detail').textContent=`${n.name} · ${n.description||'saved component'} · ${incoming} incoming / ${outgoing} outgoing wire(s) · source ${n.id}`;drawGraph(false)}
for(const [id,mode] of [['graph-branch','branch'],['graph-all','all']])I(id).addEventListener('click',()=>{graphMode=mode;I('graph-branch').setAttribute('aria-pressed',String(mode==='branch'));I('graph-all').setAttribute('aria-pressed',String(mode==='all'));drawGraph(true)});
I('graph-scale').addEventListener('input',graphView);const graphSvg=I('tower-graph');graphSvg.addEventListener('pointerdown',e=>{if(e.target.closest('.node'))return;dragPoint=[e.clientX,e.clientY];graphSvg.setPointerCapture(e.pointerId)});graphSvg.addEventListener('pointermove',e=>{if(!dragPoint)return;graphCenter[0]-=(e.clientX-dragPoint[0])*graphSize[0]/graphSvg.clientWidth;graphCenter[1]-=(e.clientY-dragPoint[1])*graphSize[1]/graphSvg.clientHeight;dragPoint=[e.clientX,e.clientY];graphView()});graphSvg.addEventListener('pointerup',()=>{dragPoint=null});graphSvg.addEventListener('pointercancel',()=>{dragPoint=null});
fetch('media/tower-graph.json').then(r=>r.json()).then(d=>{tower=d;drawGraph()}).catch(e=>{I('graph-detail').textContent=`Graph data unavailable: ${e.message}`});
let shell;function drawShell(){if(!shell)return;const threshold=Number(I('shell-angle').value),angles=shell.inclination_degrees,count=angles.filter(a=>a>=threshold).length;I('shell-angle-value').textContent=`${threshold}°`;I('shell-count').textContent=count.toLocaleString();I('shell-count-label').textContent=`of ${angles.length.toLocaleString()} retained triangles at or above ${threshold}°`;
  const hist=Array(9).fill(0);for(const a of angles)hist[Math.min(8,Math.floor(a/10))]++;const max=Math.max(...hist),svg=I('shell-histogram');svg.replaceChildren();for(let i=0;i<9;i++){const x=35+i*64,w=46,h=220*hist[i]/max,y=256-h;svg.append(E('rect',{x,y,width:w,height:h,class:`bar ${i*10+10>=threshold?'selected':''}`}));const t=E('text',{x:x+3,y:279});t.textContent=`${i*10}°`;svg.append(t)}const line=E('line',{x1:35+threshold/90*576,y1:18,x2:35+threshold/90*576,y2:258,stroke:'#9a4b55','stroke-width':2});svg.append(line)}
I('shell-angle').addEventListener('input',drawShell);fetch('media/shell-diagnostics.json').then(r=>r.json()).then(d=>{shell=d;drawShell()}).catch(e=>{I('shell-count-label').textContent=`Geometry data unavailable: ${e.message}`});
const forceFrame=document.querySelector('.tool-frame');
if(forceFrame)forceFrame.addEventListener('load',()=>{try{const doc=forceFrame.contentDocument;const fit=()=>{forceFrame.style.height=`${Math.max(420,doc.body.scrollHeight+2)}px`};fit();new ResizeObserver(fit).observe(doc.body)}catch{}});
